### ISSUE TITLE
I have changed my repo name and have to update the link in index.md

### ISSUE THREAD

**Issue by rxhxt** [ISTESRMNCR/CODE-CAMP-2020#69]
do i update the link and send a pull request again with the new link.
Team "Constant Variables"

**Comment by Uyadav207** [comment]
@rxhxt , https://github.com/ISTESRMNCR/CODE-CAMP-2020/issues/68#issuecomment-663021962

**Comment by Serhazor** [comment]
Hiya, checked the code but the only place I could see anything with a link to github was in index.js 

Are you looking to change the link in the <button> ?

**Comment by Uyadav207** [comment]
Hey! @Serhazor, thanks for taking interest. But don't think this issue requires any change in the website. But Thanks for your support.

**Comment by KaranBengani** [comment]
When will the list be out for the teams who made it through the first round of evaluation?

**Comment by Uyadav207** [comment]
@KaranBengani , This issue is closed, I merely saw your query, please make it up to issue's section.

FIrst Evaluation [ Divided into 2 parts ]

1. Documentaion ( Status [ DONE ] )
2. CODE i.e neatness and percentage complete ( Status [ Pending ] )

* Requesting you to push the code for Evaluation Round... by 10 PM Today i.e  ( 25th July, 2020 )
* When the Score sums and will get back to you. and will announce the finalist in the group itself don't worry.

From now please create a new issue section. I can't look after CLOSED ISSUES... CLOSED ISSUE MEANS THE ISSUE IS RESOLVED if may i say.
